INSERT INTO Books (Title, Author, Tropes, Description, AverageRating)
VALUES 
('Birthday Girl', 'Penelope Douglas', 'age gap, forbidden', 'A young woman falls for her boyfriend''s father.', 4.3),
('Twisted Love', 'Ana Huang', 'brother''s best friend, grumpy sunshine', 'A cold billionaire falls for his best friend''s sister.', 4.5),
('Forged in Blood', 'Sadie Kincaid', 'mafia, enemies to lovers', 'A woman is forced to marry a dangerous mafia boss.', 4.4),
('The Ballad of Never After', 'Stephanie Garber', 'fantasy, enemies to lovers', 'The sequel to Once Upon a Broken Heart.', 4.6),
('A Curse for True Love', 'Stephanie Garber', 'fantasy, amnesia, true love', 'The final book in the Once Upon a Broken Heart series.', 4.7),
('The Love Hypothesis', 'Ali Hazelwood', 'fake dating, academia', 'A PhD student fake dates a young professor.', 4.6),
('People We Meet on Vacation', 'Emily Henry', 'friends to lovers, road trip', 'Two best friends go on a summer trip that changes everything.', 4.4),
('It Ends With Us', 'Colleen Hoover', 'emotional, second chance', 'A woman navigates a difficult relationship and past trauma.', 4.3),
('Ugly Love', 'Colleen Hoover', 'angsty, emotional', 'A nurse and a pilot with a tragic past.', 4.2),
('November 9', 'Colleen Hoover', 'dual timeline, emotional', 'Two people meet on the same date every year.', 4.4),
('Verity', 'Colleen Hoover', 'dark, suspense, romance', 'A writer discovers a hidden manuscript with dark secrets.', 4.4),
('Reminders of Him', 'Colleen Hoover', 'emotional, redemption', 'A young mother tries to reconnect with her daughter.', 4.6),
('The Deal', 'Elle Kennedy', 'college, sports romance', 'A hockey player tutors a girl in exchange for fake dating.', 4.5),
('The Mistake', 'Elle Kennedy', 'college, friends to lovers', 'A hockey player realizes he made a mistake letting her go.', 4.3),
('The Score', 'Elle Kennedy', 'college, playboy falls first', 'A hockey player falls for his best friend''s ex.', 4.4),
('The Goal', 'Elle Kennedy', 'college, unexpected pregnancy', 'A hockey player and a pre-law student navigate an unplanned pregnancy.', 4.4),
('Beautiful Disaster', 'Jamie McGuire', 'bad boy, college', 'A good girl falls for a tattooed fighter.', 4.1),
('Walking Disaster', 'Jamie McGuire', 'bad boy POV', 'The same story from the bad boy''s perspective.', 4.2),
('Wallbanger', 'Alice Clayton', 'neighbors, enemies to lovers', 'A woman is annoyed by her noisy neighbor.', 4.2),
('On Dublin Street', 'Samantha Young', 'roommates, emotional', 'A woman with a tragic past moves in with a Scottish man.', 4.3),
('Thoughtless', 'S.C. Stephens', 'love triangle, emotional', 'A woman falls for her boyfriend''s best friend.', 4.1),
('Hopeless', 'Colleen Hoover', 'emotional, trauma', 'A girl with a dark past meets a mysterious boy.', 4.3),
('Maybe Someday', 'Colleen Hoover', 'musician, emotional', 'A girl discovers her neighbor is a musician with a secret.', 4.4),
('Archer''s Voice', 'Mia Sheridan', 'small town, mute hero', 'A woman helps a mute man find his voice and love.', 4.5),
('The Kiss Quotient', 'Helen Hoang', 'autistic heroine, fake dating', 'A woman with Asperger''s hires an escort to teach her about intimacy.', 4.6),
('The Bride Test', 'Helen Hoang', 'arranged marriage, immigrant story', 'A Vietnamese woman moves to America for an arranged marriage.', 4.5),
('The Heart Principle', 'Helen Hoang', 'autistic burnout, emotional', 'A woman dealing with burnout and family pressure finds love.', 4.4),
('Red, White & Royal Blue', 'Casey McQuiston', 'LGBTQ+, enemies to lovers', 'The son of the US president falls for a British prince.', 4.7),
('One Last Stop', 'Casey McQuiston', 'LGBTQ+, time travel', 'A girl falls for a woman trapped on a subway from the 1970s.', 4.5),
('Beach Read', 'Emily Henry', 'writers, enemies to lovers', 'Two rival writers swap genres for the summer.', 4.5),
('Punk 57', 'Penelope Douglas', 'enemies to lovers, pen pals', 'Two pen pals meet in person and hate each other.', 4.3),
('Credence', 'Penelope Douglas', 'taboo, forbidden', 'A girl moves in with her estranged step-uncle and cousins.', 4.1),
('The Fine Print', 'Lauren Asher', 'workplace, grumpy sunshine', 'A Disney-like park owner falls for an employee.', 4.4),
('Terms and Conditions', 'Lauren Asher', 'marriage of convenience', 'A CEO enters a marriage contract with his assistant.', 4.3),
('Final Offer', 'Lauren Asher', 'second chance, emotional', 'A man returns to his hometown to sell his late grandfather''s house.', 4.3),
('Binding 13', 'Chloe Walsh', 'sports romance, emotional', 'A rugby player falls for a girl with a traumatic past.', 4.6),
('Keeping 13', 'Chloe Walsh', 'sports romance, emotional', 'The sequel to Binding 13.', 4.7),
('Saving 6', 'Chloe Walsh', 'sports romance, emotional', 'Follows another couple in the same series.', 4.5),
('Taming 7', 'Chloe Walsh', 'sports romance, emotional', 'Another book in the Boys of Tommen series.', 4.5),
('Icebreaker', 'Hannah Grace', 'college, sports romance', 'A figure skater and hockey player share a rink and fall in love.', 4.5),
('Wildfire', 'Hannah Grace', 'summer camp, friends to lovers', 'Two camp counselors reconnect after a one-night stand.', 4.4),
('Daydream', 'Hannah Grace', 'college, slow burn', 'A hockey player and a girl dealing with burnout.', 4.4),
('Things We Never Got Over', 'Lucy Score', 'small town, grumpy sunshine', 'A runaway bride helps a grumpy tattoo artist with his niece.', 4.5),
('Things We Hide From The Light', 'Lucy Score', 'small town, emotional', 'A police chief recovering from being shot.', 4.4),
('Things We Left Behind', 'Lucy Score', 'small town, enemies to lovers', 'A lawyer and a bookshop owner with a past.', 4.5);